use_frameworks!

target 'Reinstate_Example' do
  pod 'Reinstate', :path => '../'

  target 'Reinstate_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
